server:
    port: 4555

spring:
    datasource:
        url: jdbc:mysql://185.106.128.200:3306/cdsoft1_temp
        username: cdsoft1_barak
        password: Barak1234!
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

#CLEARDB_DATABASE_URL
#mysql://b3e56e505281f6:fa050b58@eu-cdbr-west-03.cleardb.net/heroku_e2afeb1a70347c7?reconnect=true
#        url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_e2afeb1a70347c7
#        username: b3e56e505281f6
#        password: fa050b58