server:
    port: 4555

spring:
    datasource:
        url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_91eac397761141f
        username: b0f1eff7dacdc6
        password: df351b43
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            mode: always