server:
    port: 4555

spring:
    datasource:
        url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_e2afeb1a70347c7
        username: b3e56e505281f6
        password: fa050b58
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            mode: always